hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
  routes:
    course:
      path: /users/**
      service-id: course-service
      stripPrefix: false
      sensitiveHeaders:
    user:
      path: /user-api/**
      service-id: user-service
      stripPrefix: false
      sensitiveHeaders:

spring:
  application:
    name: api-gateway
